client/src/Screens/editprofilescreen.jsx
client/src/Screens/loginscreen.jsx
client/src/Screens/newpassscreen.jsx
client/src/Screens/registerscreen.jsx
client/src/Screens/resetpassscreen.jsx

- แก้ css นิดหน่อย เพิ่มพวกตัวหนาใน inlinestyle
- ใส่ useStete ทุกหน้า
- แต่พวก handlesave กับ handlecancel ยังงงๆ
- หน้า login กด signup จะ Link ไปยัง registerpage กดปุ่ม forgetpass จะ Link ไปหน้า resetpass
- 
- หน้าที่กดปุ่ม cancel จะ Link กลับไปยัง login page
1. newpass
2. register
3. resetpass

add useStete and link to path

---

client/index.html
client/src/Screens/LandingPage.jsx
client/src/assets/css/components/navbar.css
client/src/assets/css/main_style.css
client/src/components/Navbar.jsx
client/src/main.jsx

Navbar Component completed

---

README.md

Readme for project installation.

---

client/package-lock.json
client/package.json
client/src/assets/css/components/GoalProgress.css
client/src/assets/css/components/UserProfile.css
client/src/components/GoalProgress.jsx
client/src/components/UserProfile.jsx
client/src/layout/DashboardLayout/Dashboard.jsx
client/src/main.jsx

Dashboard Create , Still Have to fix space from nav to UserProfile

---

client/src/assets/css/DashboardScreen.css
client/src/assets/css/main_style.css
client/src/layout/DashboardLayout/Dashboard.jsx

Fix Dashboard screen navbar and user profile Fixed position

---

server/controllers/activityController.js
server/index.js
server/models/Activity.js
server/routes/activities.js

Express MVC Data analysation

---

server/controllers/activityController.js
server/routes/activities.js

test slack alert

---

client/src/assets/css/components/Success.css
client/src/components/Success.jsx

stages approved

---

client/src/Screens/LandingPage.jsx
client/src/assets/css/LandingPage.css
client/src/components/ActivityDetail.jsx
client/src/components/GoalSelection.jsx
client/src/components/SpecificGoal.jsx
client/src/main.jsx

Fix React code

---

client/src/testConflict.jsx

text/Conflict pls V.2

---

client/src/testConflict.jsx

conflict edit test

---

server/controllers/arlif/activityDeleteController.js
server/controllers/arlif/activityShowOneController.js

arlif Activity ShowOne and Delete done

---

server/controllers/boom/activityAddController.js
server/controllers/boom/activityAllController.js
server/models/Activity.js
server/routes/activities.js

API Boom Done

---

client/src/Screens/EditProfileScreen.jsx
client/src/Screens/RegisterScreen.jsx
client/src/Screens/ResetPassScreen.jsx

screen
resetpass
register
editprofile

fix tight box + edit margin css inline 

---

server/controllers/plug/userGetDataController.js
server/controllers/plug/userRegisterController.js
server/index.js
server/models/User.js
server/package-lock.json
server/package.json
server/routes/activities.js
server/routes/users.js

Featuer user register finish waiting for validate

---

server/controllers/plug/userGetDataController.js
server/routes/users.js

LG, Feature get user profile before login.

Feature get user data before login completed

---

server/controllers/pang/userVerifyResetPasswordController.js
server/routes/users.js

Change verify password from id to email

Done change check from email instead of id

---

server/controllers/plug/userRegisterController.js

fix bug feature user register

---

client/src/Screens/RegisterScreen.jsx
server/controllers/plug/userRegisterController.js

Check file type and isLoading setup

---

client/src/Screens/RegisterScreen.jsx
client/src/main.jsx

React set base url

---

server/controllers/toey/userEditProfileController.js

delete user image with public id

---

server/controllers/toey/activityEditController.js

use toey key 
please edit to boom(activity) and plug(user) key

delete image on cloudinary at activity

---

client/src/Screens/EditProfileScreen.jsx
client/src/Screens/LoginScreen.jsx
client/src/Screens/RegisterScreen.jsx
client/src/Screens/ResetPassScreen.jsx

edit input css in auth screen

---

server/controllers/vee/userGoalSuccessController.js
server/controllers/vee/userUpdateGoalWeightController.js

controller vee update

---

server/controllers/boom/activityAddController.js
server/controllers/deleteCloudinaryImage.js
server/controllers/toey/activityEditController.js
server/controllers/toey/userEditProfileController.js
server/index.js

Set cloudinary env

---

server/index.js

merge set root path to develop.

Set root path.

---

server/package.json

Set scripts start

---

server/index.js
server/package.json

Set start index

---

package.json

Sure Deploy Confirm exaxly

---

server/controllers/boom/activityAddController.js

chancg cloudianary KBoom file

---

client/src/Screens/LoginScreen.jsx
client/src/components/GoalSelection.jsx
client/src/layout/DashboardLayout/Dashboard.jsx
server/controllers/plug/userLoginController.js

Fix bug login fail not show error and set goal weight by idol and config

---

server/controllers/plug/userGetDataController.js

Add catch user data

---

client/src/assets/css/components/CRUD.css
client/src/components/CrudCreate.jsx
server/models/Activity.js

Add Activity Page Validator done with Img preview and also alert

Crud create img prev validate

---

client/src/Screens/ActivityCardScreen.jsx
client/src/components/ActivityCard.jsx
client/src/components/CrudCreate.jsx

Reverts pramotepon/reborn-giwon#123

Revert "fetchData ActivityShow"

---

client/src/Screens/ActivityCardScreen.jsx
client/src/components/ActivityCard.jsx

ActivitieShow from Database without CSS

---

server/controllers/boom/activityAddController.js
server/models/Activity.js

Add current weight of each activity to Schema and API

---

client/src/Screens/EditProfileScreen.jsx
client/src/Screens/NewPassScreen.jsx
client/src/Screens/ResetPassScreen.jsx
server/controllers/pang/userResetPassword.js
server/controllers/pang/userVerifyResetPasswordController.js

User can verify check and reset password

---

client/src/Screens/EditProfileScreen.jsx
server/controllers/toey/userEditProfileController.js

User can edit and back to dashboard

---

client/src/Screens/EditProfileScreen.jsx
server/controllers/toey/userEditProfileController.js
server/routes/users.js
server/utils/userGetId.js
server/utils/verifyToken.js

Fix User Edit

---

client/src/Screens/LandingPage.jsx

Landing page set user and toggle class nav bar

---

client/src/components/Navbar.jsx

Dashboard logo link to /dashboard

---

client/src/assets/css/DashboardScreen.css
client/src/assets/css/components/buttonNewActivity.css
client/src/assets/css/components/navbar.css
client/src/components/ButtonNewActivity.jsx
client/src/components/Navbar.jsx
client/src/layout/DashboardLayout/Dashboard.jsx

Profile user responsive

---

client/src/components/ButtonNewActivity.jsx

Fix button add new activity, Merge to production

Fix btn add new activity

---

client/src/Screens/LandingPage.jsx
client/src/assets/css/LandingPage.css
client/src/assets/css/root.css

Fix font weight

---

client/src/assets/css/LandingPage.css

Set card review height

---

client/src/Screens/LandingPage.jsx

deploy without img

---

client/src/Screens/LoginScreen.jsx
client/src/assets/css/components/ActivityCard.css
client/src/assets/css/components/CRUD.css
client/src/components/ActivityCard.jsx
client/src/components/CrudCreate.jsx

edit css and some text

---

client/src/Screens/ResetPassScreen.jsx
server/controllers/UserController.js

Form reset password and loading successfully.

Fix form reset password completed

---

client/src/assets/css/components/IsLoading.css
client/src/components/CrudCreate.jsx
client/src/components/IsLoadingComponent.jsx

Loading component position in add activity and set max date Completed.

Loading component position in add activity and set max date Completed

---

README.md
client/src/Screens/LandingPage.jsx
client/src/components/GoalProgress.jsx
client/src/components/Success.jsx

merge to production

---

client/src/components/CrudCreate.jsx

User edit profile.

---

client/package-lock.json
client/package.json
client/src/Screens/ActivityCardScreen.jsx
client/src/components/ActivityCard.jsx
client/src/components/ActivityDetail.jsx

Facebook share

---

client/index.html
client/src/main.jsx

Set og:image in main.jsx

---

client/index.html
client/src/Screens/LoginScreen.jsx
client/src/Screens/RegisterScreen.jsx
client/src/Screens/ResetPassScreen.jsx
client/src/components/ActivityCard.jsx
client/src/components/ActivityCardEdit.jsx
client/src/components/CrudCreate.jsx
client/src/main.jsx

Add og image in index by cloud

---

client/index.html
client/src/Screens/LoginScreen.jsx
client/src/Screens/RegisterScreen.jsx
client/src/Screens/ResetPassScreen.jsx
client/src/components/ActivityCard.jsx
client/src/components/ActivityCardEdit.jsx
client/src/components/CrudCreate.jsx
client/src/main.jsx

Add og image in index by cloud

Add og image in index by cloud, Deploy

---

client/src/assets/css/LandingPage.css

Animation card landing page

---

README.md

edit readme project about
